version: '3'
services:
  tracing:
    image: 'jaegertracing/all-in-one:1.27'
    hostname: 'jaeger'
    container_name: 'jaeger'
    ports:
      - '6831:6831/udp'
      - '16686:16686'
      - '14250:14250'
  server:
    image: '$name$-server:latest'
    hostname: '$name$-server'
    container_name: '$name$-server'
    depends_on:
      - tracing
    ports:
      - '8080:8080'
      - '8081:8081'
    environment:
      SERVER_PORT: 8080
      HTTP_METRICS_PORT: 8081
      TRACING_AGENT_HOST: 'jaeger'
      TRACING_AGENT_PORT: 6831
      TRACING_SERVICE_NAME: 'server'
  client:
    image: '$name$-client:latest'
    hostname: '$name$-client'
    container_name: '$name$-client'
    depends_on:
      - tracing
      - server
    ports:
      - '8082:8082'
    environment:
      SERVER_HOST: '$name$-server'
      SERVER_PORT: 8080
      HTTP_METRICS_PORT: 8082
      TRACING_AGENT_HOST: 'jaeger'
      TRACING_AGENT_PORT: 6831
      TRACING_SERVICE_NAME: 'client'

