version: '3'
services:
  tracing:
    image: 'jaegertracing/all-in-one:1.27'
    hostname: 'jaeger'
    container_name: 'jaeger'
    ports:
      - '6831:6831/udp'
      - '16686:16686'
      - '14250:14250'
  server:
    image: '$name$-server:latest'
    hostname: '$name$-server'
    container_name: '$name$-server'
    depends_on:
      - tracing
    ports:
      - '8080:8080'
      - '8081:8081'
  client:
    image: '$name$-client:latest'
    hostname: '$name$-client'
    container_name: '$name$-client'
    depends_on:
      - tracing
      - server
    ports:
      - '8082:8082'
